"""add microsoft GUID to user model

Revision ID: 300f24071c14
Revises: 4fa893cdd432
Create Date: 2024-04-06 10:15:35.146272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300f24071c14'
down_revision = '4fa893cdd432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acm_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microsoft_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['microsoft_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acm_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('microsoft_id')

    # ### end Alembic commands ###
