"""add event checkins

Revision ID: 53a76e988b5a
Revises: 300f24071c14
Create Date: 2024-08-25 15:18:22.451548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a76e988b5a'
down_revision = '300f24071c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acm_checkins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event'], ['acm_events.id'], ),
    sa.ForeignKeyConstraint(['user'], ['acm_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acm_checkins')
    # ### end Alembic commands ###
